apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-lab17
  labels:
    app: backend-lab17 
spec:
  selector:
    matchLabels:
      app: backend-lab17 
  replicas: 1
  template:
    metadata:
      labels:
        app: backend-lab17 
    spec:
      containers:
        - name: backend-lab17 
          image: hooni26/backend-lab17 
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
