apiVersion: v1
kind: Service
metadata:
  name: backend-lab17 
  labels:
    name: backend-lab17 
spec:
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
  selector:
    app: backend-lab17 
  type: NodePort
